Coordinate trainer: implement an untimed mode

diff --git a/ui/build b/ui/build
--- a/ui/build
+++ b/ui/build
@@ -4,8 +4,11 @@ target=${1-dev}
 mode=${2-build} # build | upgrade | css | js
 echo "building ui modules with target=$target and mode=$mode"
 
-echo "node: $(node --version)"
+nodever="$(node --version)"
+echo "node: $nodever"
 echo "yarn: $(yarn --version)"
+
+[[ "$nodever" =~ ^(v14\.1[3-9]\.[0-9]+)|(v1[5-8]\.[0-9]+\.[0-9]+)$ ]] || { echo "Node version >=14.13 and <=18 required. Found: $nodever"; exit 1; }
 
 cd "$(git rev-parse --show-toplevel)"
 
@@ -14,8 +17,10 @@ ls -l node_modules node_modules/@* ui/node_modules ui/*/node_modules | grep /yar
 mkdir -p public/compiled
 
 apps1="common"
-apps2="ceval game tree chat nvui puz"
-apps3="site msg chat cli challenge notify learn editor round analyse lobby tournament tournamentSchedule tournamentCalendar simul dasher speech palantir serviceWorker puzzle storm coordinateTrainer"
+apps2="palantir"
+apps3="ceval game tree chat nvui puz"
+apps4="site msg cli challenge notify learn editor puzzle round analyse lobby tournament tournamentSchedule tournamentCalendar simul dasher serviceWorker storm coordinateTrainer "
+site_plugins="speech"
 
 if [ $mode == "upgrade" ]; then
   yarn upgrade --non-interactive
@@ -36,9 +41,22 @@ build() {
   fi
 }
 
+build_plugin() {
+  echo $1
+  module="$(cut -d':' -f1 <<<$1)"
+  plugin="$(cut -d':' -f2 <<<$1)"
+  echo "### ui/$module plugin $plugin ###"
+  set -ev
+  cd ui/$module
+  yarn run plugin-$target $plugin
+}
+
+build_site_plugin() {
+  build_plugin "site:$1"
+}
 
 if [ $mode != "upgrade" ] && [ $mode != "js" ]; then
-  apps3="css $apps3"
+  apps4="css $apps4"
 fi
 
 if [ $mode == "css" ]; then
@@ -47,14 +65,16 @@ else
   if type -p parallel; then # parallel execution!
     if [ -z "$P_OPTS" -a ! -e ~/.parallel/config ]; then
       P_OPTS="-j+4 --halt 2"
-      [ -n "$GITHUB_WORKFLOW" ] || P_OPTS+=" --bar"
     fi
     set -x
     parallel --gnu $P_OPTS build ::: $apps1
     parallel --gnu $P_OPTS build ::: $apps2
     parallel --gnu $P_OPTS build ::: $apps3
+    parallel --gnu $P_OPTS build ::: $apps4
+    parallel --gnu $P_OPTS build_site_plugin ::: $site_plugins
   else # sequential execution
     echo "For faster builds, install GNU parallel."
-    for app in $apps1 $apps2 $apps3; do (build $app); done
+    for app in $apps1 $apps2 $apps3 $apps4; do (build $app); done
+    for plugin in $site_plugins; do (build_site_plugin $plugin); done
   fi
 fi
